name: example
description: Example for cli_completion
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion:
    path: ../
  mason_logger: ^0.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^8.0.0

executables:
  example_cli:
