name: cli_completion
description: Completion toolkit for Command runner based Dart CLIs
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  equatable: ^2.0.5
  mason_logger: ^0.2.2
  meta: ^1.8.0
  path: ^1.8.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
